export const categories = [
  {
    code: 'laptops',
    name: 'Laptops',
    children: [
      {
        code: 'business-laptops',
        name: 'Business Laptops',
        children: [],
      },
    ],
  },
  {
    code: 'audio',
    name: 'Audio',
    children: [
      {
        code: 'headphones',
        name: 'Headphones',
        children: [],
      },
    ],
  },
  {
    code: 'monitors',
    name: 'Monitors',
    children: [
      {
        code: 'gaming-monitors',
        name: 'Gaming Monitors',
        children: [],
      },
    ],
  },
];

export const products = [
  {
    id: '100',
    masterProductId: 'mp-100',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'lenovo-thinkpad',
    title: 'Lenovo ThinkPad X1 Carbon Gen',
    brand: 'Lenovo',
    manufacturerCode: '21NS001PBM',
    categoryIds: ['laptops', 'business-laptops'],
    description:
      'Light business laptop with OLED display, long battery life, and durable chassis for everyday work.',
    seo: {
      title: 'Lenovo ThinkPad X1 Carbon Gen',
      description: 'Business laptop with OLED display and long battery life.',
    },
    badges: [{ code: 'business-choice', label: 'Business choice', tone: 'success' }],
    price: {
      current: { amount: 3699, currencyCode: 'BGN' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'inStock',
      storesAvailableCount: 12,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
        altText: 'Lenovo ThinkPad laptop on a desk',
        role: 'primary',
      },
      {
        url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
        altText: 'Open laptop on a workspace',
        role: 'gallery',
      },
    ],
    specs: [
      {
        code: 'cpu',
        label: 'Processor',
        value: 'Intel Core Ultra 7',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
      {
        code: 'memory',
        label: 'Memory',
        value: '32',
        unit: 'GB LPDDR5x',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
      {
        code: 'storage',
        label: 'Storage',
        value: '1',
        unit: 'TB NVMe SSD',
        groupCode: 'storage',
        groupLabel: 'Storage',
        comparable: true,
        filterable: true,
      },
      {
        code: 'display',
        label: 'Display',
        value: '14 inch OLED, 120 Hz',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [
      {
        id: 'v-100-1',
        label: '32GB / 1TB',
        sku: 'X1-32-1TB',
        attributes: [
          { code: 'memory', label: 'Memory', value: '32', unit: 'GB' },
          { code: 'storage', label: 'Storage', value: '1', unit: 'TB' },
        ],
        availability: { status: 'inStock', storesAvailableCount: 12 },
        isDefault: true,
      },
      {
        id: 'v-100-2',
        label: '16GB / 512GB',
        sku: 'X1-16-512',
        attributes: [
          { code: 'memory', label: 'Memory', value: '16', unit: 'GB' },
          { code: 'storage', label: 'Storage', value: '512', unit: 'GB' },
        ],
        price: {
          current: { amount: 3299, currencyCode: 'BGN' },
          includesTax: true,
          taxRate: 20,
        },
        availability: { status: 'inStock', storesAvailableCount: 8 },
        isDefault: false,
      },
      {
        id: 'v-100-3',
        label: '64GB / 2TB',
        sku: 'X1-64-2TB',
        attributes: [
          { code: 'memory', label: 'Memory', value: '64', unit: 'GB' },
          { code: 'storage', label: 'Storage', value: '2', unit: 'TB' },
        ],
        availability: { status: 'outOfStock' },
        isDefault: false,
      },
    ],
    stockStatus: 'inStock',
  },
  {
    id: '101',
    masterProductId: 'mp-101',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'sony-wh-1000xm6',
    title: 'Sony WH-1000XM6 Noise Canceling Headphones',
    brand: 'Sony',
    manufacturerCode: 'WH1000XM6B.CE7',
    categoryIds: ['audio', 'headphones'],
    description:
      'Wireless headphones with active noise canceling, long battery life, and detailed sound for travel and work.',
    seo: {
      title: 'Sony WH-1000XM6 Noise Canceling Headphones',
      description: 'Sony wireless headphones with active noise canceling.',
    },
    badges: [{ code: 'promo', label: 'Promo', tone: 'warning' }],
    price: {
      current: { amount: 829, currencyCode: 'BGN' },
      original: { amount: 899, currencyCode: 'BGN' },
      discountPercent: 8,
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'limited',
      quantity: 4,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
        altText: 'Sony wireless headphones',
        role: 'primary',
      },
      {
        url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80',
        altText: 'Headphones on a desk',
        role: 'gallery',
      },
    ],
    specs: [
      {
        code: 'noise-canceling',
        label: 'Noise canceling',
        value: 'Active noise canceling',
        groupCode: 'audio',
        groupLabel: 'Audio',
        comparable: true,
        filterable: true,
      },
      {
        code: 'battery-life',
        label: 'Battery',
        value: '30',
        unit: 'hours',
        groupCode: 'battery',
        groupLabel: 'Battery',
        comparable: true,
        filterable: true,
      },
      {
        code: 'connection',
        label: 'Connection',
        value: 'Bluetooth',
        groupCode: 'connectivity',
        groupLabel: 'Connectivity',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [
      {
        id: 'v-101-1',
        label: 'Black',
        sku: 'WH1000XM6-B',
        attributes: [{ code: 'color', label: 'Color', value: 'Black' }],
        availability: { status: 'limited', quantity: 4 },
        isDefault: true,
      },
      {
        id: 'v-101-2',
        label: 'Silver',
        sku: 'WH1000XM6-S',
        attributes: [{ code: 'color', label: 'Color', value: 'Silver' }],
        availability: { status: 'outOfStock' },
        isDefault: false,
      },
    ],
    stockStatus: 'limited',
  },
  {
    id: '102',
    masterProductId: 'mp-102',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'samsung-odyssey-oled',
    title: 'Samsung Odyssey OLED 32 Gaming Monitor',
    brand: 'Samsung',
    manufacturerCode: 'LS32DG802SUXEN',
    categoryIds: ['monitors', 'gaming-monitors'],
    description:
      '32-inch OLED gaming monitor with high refresh rate, deep contrast, and fast response.',
    seo: {
      title: 'Samsung Odyssey OLED 32 Gaming Monitor',
      description: '32-inch Samsung Odyssey OLED gaming monitor.',
    },
    badges: [{ code: 'online-only', label: 'Online only', tone: 'neutral' }],
    price: {
      current: { amount: 2199, currencyCode: 'BGN' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'onlineOnly',
      estimatedDeliveryDate: '2026-05-14',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80',
        altText: 'Samsung Odyssey gaming monitor',
        role: 'primary',
      },
      {
        url: 'https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=1200&q=80',
        altText: 'Gaming monitor on a desk',
        role: 'gallery',
      },
    ],
    specs: [
      {
        code: 'screen-size',
        label: 'Size',
        value: '32',
        unit: 'inch',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
      {
        code: 'panel',
        label: 'Panel',
        value: 'OLED',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
      {
        code: 'refresh-rate',
        label: 'Refresh rate',
        value: '240',
        unit: 'Hz',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [
      {
        id: 'v-102-1',
        label: '32 inch OLED',
        sku: 'ODY-OLED-32',
        attributes: [
          { code: 'screen-size', label: 'Size', value: '32', unit: 'inch' },
          { code: 'panel', label: 'Panel', value: 'OLED' },
        ],
        availability: {
          status: 'onlineOnly',
          estimatedDeliveryDate: '2026-05-14',
        },
        isDefault: true,
      },
    ],
    stockStatus: 'inStock',
  },
];
