export const categories = [
  {
    code: 'phones',
    name: 'Phones',
    children: [],
  },
  {
    code: 'laptops',
    name: 'Laptops',
    children: [
      {
        code: 'business-laptops',
        name: 'Business Laptops',
        children: [],
      },
    ],
  },
  {
    code: 'audio',
    name: 'Audio',
    children: [
      {
        code: 'headphones',
        name: 'Headphones',
        children: [],
      },
    ],
  },
  {
    code: 'monitors',
    name: 'Monitors',
    children: [
      {
        code: 'gaming-monitors',
        name: 'Gaming Monitors',
        children: [],
      },
    ],
  },
];

export const products = [
  {
    id: '200',
    masterProductId: 'mp-200',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'samsung-galaxy-s25',
    title: 'Samsung Galaxy S25 128GB',
    brand: 'Samsung',
    manufacturerCode: 'SM-S931BZKDEUE',
    categoryIds: ['phones'],
    description:
      'Compact Samsung smartphone with bright display, long battery life, and 128GB storage.',
    seo: {
      title: 'Samsung Galaxy S25 128GB',
      description: 'Samsung smartphone with 4000 mAh battery and 128GB storage.',
    },
    badges: [{ code: 'new', label: 'New', tone: 'success' }],
    price: {
      current: { amount: 899.99, currencyCode: 'EUR' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'inStock',
      storesAvailableCount: 9,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80',
        altText: 'Samsung Galaxy smartphone',
        role: 'primary',
      },
    ],
    specs: [
      {
        code: 'model',
        label: 'Model',
        value: 'Galaxy S25',
        groupCode: 'general',
        groupLabel: 'General',
        comparable: true,
        filterable: true,
      },
      {
        code: 'battery',
        label: 'Battery',
        value: '4000',
        unit: 'mAh',
        groupCode: 'battery',
        groupLabel: 'Battery',
        comparable: true,
        filterable: true,
      },
      {
        code: 'storage',
        label: 'Storage',
        value: '128GB',
        groupCode: 'storage',
        groupLabel: 'Storage',
        comparable: true,
        filterable: true,
      },
      {
        code: 'ram',
        label: 'RAM',
        value: '8 - 12 GB',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [],
    stockStatus: 'inStock',
  },
  {
    id: '201',
    masterProductId: 'mp-201',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'samsung-galaxy-s25-plus',
    title: 'Samsung Galaxy S25+ 256GB',
    brand: 'Samsung',
    manufacturerCode: 'SM-S936BZBGEUE',
    categoryIds: ['phones'],
    description:
      'Large Samsung smartphone with high capacity battery and 256GB storage.',
    seo: {
      title: 'Samsung Galaxy S25+ 256GB',
      description: 'Samsung smartphone with 4900 mAh battery and 256GB storage.',
    },
    badges: [{ code: 'top-seller', label: 'Top seller', tone: 'success' }],
    price: {
      current: { amount: 1099.99, currencyCode: 'EUR' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'limited',
      quantity: 5,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80',
        altText: 'Samsung Galaxy phone',
        role: 'primary',
      },
    ],
    specs: [
      {
        code: 'model',
        label: 'Model',
        value: 'Galaxy S25+',
        groupCode: 'general',
        groupLabel: 'General',
        comparable: true,
        filterable: true,
      },
      {
        code: 'battery',
        label: 'Battery',
        value: '4900',
        unit: 'mAh',
        groupCode: 'battery',
        groupLabel: 'Battery',
        comparable: true,
        filterable: true,
      },
      {
        code: 'storage',
        label: 'Storage',
        value: '256GB',
        groupCode: 'storage',
        groupLabel: 'Storage',
        comparable: true,
        filterable: true,
      },
      {
        code: 'ram',
        label: 'RAM',
        value: '8 - 12 GB',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [],
    stockStatus: 'limited',
  },
  {
    id: '202',
    masterProductId: 'mp-202',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'xiaomi-14t-pro',
    title: 'Xiaomi 14T Pro 256GB',
    brand: 'Xiaomi',
    manufacturerCode: 'MZB0H2WEU',
    categoryIds: ['phones'],
    description:
      'Xiaomi smartphone with fast charging, 5000 mAh battery, and 256GB storage.',
    seo: {
      title: 'Xiaomi 14T Pro 256GB',
      description: 'Xiaomi smartphone with 5000 mAh battery and 256GB storage.',
    },
    badges: [{ code: 'promo', label: 'Promo', tone: 'warning' }],
    price: {
      current: { amount: 749.99, currencyCode: 'EUR' },
      original: { amount: 799.99, currencyCode: 'EUR' },
      discountPercent: 6,
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'inStock',
      storesAvailableCount: 15,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80',
        altText: 'Xiaomi smartphone',
        role: 'primary',
      },
    ],
    specs: [
      {
        code: 'model',
        label: 'Model',
        value: '14T Pro',
        groupCode: 'general',
        groupLabel: 'General',
        comparable: true,
        filterable: true,
      },
      {
        code: 'battery',
        label: 'Battery',
        value: '5000',
        unit: 'mAh',
        groupCode: 'battery',
        groupLabel: 'Battery',
        comparable: true,
        filterable: true,
      },
      {
        code: 'storage',
        label: 'Storage',
        value: '256GB',
        groupCode: 'storage',
        groupLabel: 'Storage',
        comparable: true,
        filterable: true,
      },
      {
        code: 'ram',
        label: 'RAM',
        value: '12 GB',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [],
    stockStatus: 'inStock',
  },
  {
    id: '203',
    masterProductId: 'mp-203',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'xiaomi-redmi-note-14',
    title: 'Xiaomi Redmi Note 14 128GB',
    brand: 'Xiaomi',
    manufacturerCode: 'MZB0I1WEU',
    categoryIds: ['phones'],
    description:
      'Affordable Xiaomi smartphone with 128GB storage and large battery.',
    seo: {
      title: 'Xiaomi Redmi Note 14 128GB',
      description: 'Xiaomi smartphone with 5110 mAh battery and 128GB storage.',
    },
    badges: [{ code: 'value', label: 'Best value', tone: 'neutral' }],
    price: {
      current: { amount: 249.99, currencyCode: 'EUR' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'inStock',
      storesAvailableCount: 22,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80',
        altText: 'Xiaomi Redmi smartphone',
        role: 'primary',
      },
    ],
    specs: [
      {
        code: 'model',
        label: 'Model',
        value: 'Redmi Note 14',
        groupCode: 'general',
        groupLabel: 'General',
        comparable: true,
        filterable: true,
      },
      {
        code: 'battery',
        label: 'Battery',
        value: '5110',
        unit: 'mAh',
        groupCode: 'battery',
        groupLabel: 'Battery',
        comparable: true,
        filterable: true,
      },
      {
        code: 'storage',
        label: 'Storage',
        value: '128GB',
        groupCode: 'storage',
        groupLabel: 'Storage',
        comparable: true,
        filterable: true,
      },
      {
        code: 'ram',
        label: 'RAM',
        value: '4 - 6 GB',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [],
    stockStatus: 'inStock',
  },
  {
    id: '100',
    masterProductId: 'mp-100',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'lenovo-thinkpad',
    title: 'Lenovo ThinkPad X1 Carbon Gen',
    brand: 'Lenovo',
    manufacturerCode: '21NS001PBM',
    categoryIds: ['laptops', 'business-laptops'],
    description:
      'Light business laptop with OLED display, long battery life, and durable chassis for everyday work.',
    seo: {
      title: 'Lenovo ThinkPad X1 Carbon Gen',
      description: 'Business laptop with OLED display and long battery life.',
    },
    badges: [{ code: 'business-choice', label: 'Business choice', tone: 'success' }],
    price: {
      current: { amount: 1891.27, currencyCode: 'EUR' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'inStock',
      storesAvailableCount: 12,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80',
        altText: 'Lenovo ThinkPad laptop on a desk',
        role: 'primary',
      },
      {
        url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
        altText: 'Open laptop on a workspace',
        role: 'gallery',
      },
    ],
    specs: [
      {
        code: 'cpu',
        label: 'Processor',
        value: 'Intel Core Ultra 7',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
      {
        code: 'memory',
        label: 'Memory',
        value: '32',
        unit: 'GB LPDDR5x',
        groupCode: 'performance',
        groupLabel: 'Performance',
        comparable: true,
        filterable: true,
      },
      {
        code: 'storage',
        label: 'Storage',
        value: '1',
        unit: 'TB NVMe SSD',
        groupCode: 'storage',
        groupLabel: 'Storage',
        comparable: true,
        filterable: true,
      },
      {
        code: 'display',
        label: 'Display',
        value: '14 inch OLED, 120 Hz',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [
      {
        id: 'v-100-1',
        label: '32GB / 1TB',
        sku: 'X1-32-1TB',
        attributes: [
          { code: 'memory', label: 'Memory', value: '32', unit: 'GB' },
          { code: 'storage', label: 'Storage', value: '1', unit: 'TB' },
        ],
        availability: { status: 'inStock', storesAvailableCount: 12 },
        isDefault: true,
      },
      {
        id: 'v-100-2',
        label: '16GB / 512GB',
        sku: 'X1-16-512',
        attributes: [
          { code: 'memory', label: 'Memory', value: '16', unit: 'GB' },
          { code: 'storage', label: 'Storage', value: '512', unit: 'GB' },
        ],
        price: {
          current: { amount: 1686.75, currencyCode: 'EUR' },
          includesTax: true,
          taxRate: 20,
        },
        availability: { status: 'inStock', storesAvailableCount: 8 },
        isDefault: false,
      },
      {
        id: 'v-100-3',
        label: '64GB / 2TB',
        sku: 'X1-64-2TB',
        attributes: [
          { code: 'memory', label: 'Memory', value: '64', unit: 'GB' },
          { code: 'storage', label: 'Storage', value: '2', unit: 'TB' },
        ],
        availability: { status: 'outOfStock' },
        isDefault: false,
      },
    ],
  },
  {
    id: '101',
    masterProductId: 'mp-101',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'sony-wh-1000xm6',
    title: 'Sony WH-1000XM6 Noise Canceling Headphones',
    brand: 'Sony',
    manufacturerCode: 'WH1000XM6B.CE7',
    categoryIds: ['audio', 'headphones'],
    description:
      'Wireless headphones with active noise canceling, long battery life, and detailed sound for travel and work.',
    seo: {
      title: 'Sony WH-1000XM6 Noise Canceling Headphones',
      description: 'Sony wireless headphones with active noise canceling.',
    },
    badges: [{ code: 'promo', label: 'Promo', tone: 'warning' }],
    price: {
      current: { amount: 423.86, currencyCode: 'EUR' },
      original: { amount: 459.65, currencyCode: 'EUR' },
      discountPercent: 8,
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'limited',
      quantity: 4,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
        altText: 'Sony wireless headphones',
        role: 'primary',
      },
      {
        url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80',
        altText: 'Headphones on a desk',
        role: 'gallery',
      },
    ],
    specs: [
      {
        code: 'noise-canceling',
        label: 'Noise canceling',
        value: 'Active noise canceling',
        groupCode: 'audio',
        groupLabel: 'Audio',
        comparable: true,
        filterable: true,
      },
      {
        code: 'battery-life',
        label: 'Battery',
        value: '30',
        unit: 'hours',
        groupCode: 'battery',
        groupLabel: 'Battery',
        comparable: true,
        filterable: true,
      },
      {
        code: 'connection',
        label: 'Connection',
        value: 'Bluetooth',
        groupCode: 'connectivity',
        groupLabel: 'Connectivity',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [
      {
        id: 'v-101-1',
        label: 'Black',
        sku: 'WH1000XM6-B',
        attributes: [{ code: 'color', label: 'Color', value: 'Black' }],
        availability: { status: 'limited', quantity: 4 },
        isDefault: true,
      },
      {
        id: 'v-101-2',
        label: 'Silver',
        sku: 'WH1000XM6-S',
        attributes: [{ code: 'color', label: 'Color', value: 'Silver' }],
        availability: { status: 'outOfStock' },
        isDefault: false,
      },
    ],
  },
  {
    id: '102',
    masterProductId: 'mp-102',
    marketCode: 'bg',
    locale: 'bg-BG',
    slug: 'samsung-odyssey-oled',
    title: 'Samsung Odyssey OLED 32 Gaming Monitor',
    brand: 'Samsung',
    manufacturerCode: 'LS32DG802SUXEN',
    categoryIds: ['monitors', 'gaming-monitors'],
    description:
      '32-inch OLED gaming monitor with high refresh rate, deep contrast, and fast response.',
    seo: {
      title: 'Samsung Odyssey OLED 32 Gaming Monitor',
      description: '32-inch Samsung Odyssey OLED gaming monitor.',
    },
    badges: [{ code: 'online-only', label: 'Online only', tone: 'neutral' }],
    price: {
      current: { amount: 1124.32, currencyCode: 'EUR' },
      includesTax: true,
      taxRate: 20,
    },
    availability: {
      status: 'onlineOnly',
      estimatedDeliveryDate: '2026-05-14',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80',
        altText: 'Samsung Odyssey gaming monitor',
        role: 'primary',
      },
      {
        url: 'https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=1200&q=80',
        altText: 'Gaming monitor on a desk',
        role: 'gallery',
      },
    ],
    specs: [
      {
        code: 'screen-size',
        label: 'Size',
        value: '32',
        unit: 'inch',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
      {
        code: 'panel',
        label: 'Panel',
        value: 'OLED',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
      {
        code: 'refresh-rate',
        label: 'Refresh rate',
        value: '240',
        unit: 'Hz',
        groupCode: 'display',
        groupLabel: 'Display',
        comparable: true,
        filterable: true,
      },
    ],
    variants: [
      {
        id: 'v-102-1',
        label: '32 inch OLED',
        sku: 'ODY-OLED-32',
        attributes: [
          { code: 'screen-size', label: 'Size', value: '32', unit: 'inch' },
          { code: 'panel', label: 'Panel', value: 'OLED' },
        ],
        availability: {
          status: 'onlineOnly',
          estimatedDeliveryDate: '2026-05-14',
        },
        isDefault: true,
      },
    ],
  },
];
